# charts/auth/values.yaml
replicaCount: 2

image:
  repository: myoli999/auth-app
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8001

containerPort: 8001

database:
  writableUrl: "postgresql://scott:tiger@localhost:5432/auth_db"
  readonlyUrl: "postgresql://scott:tiger@localhost:5432/auth_db"
jwt:
  secret: "secret-key"
